@startuml
left to right direction
skinparam titleBorderRoundCorner 15
skinparam titleBorderThickness 1
skinparam titleBorderColor black
skinparam titleBackgroundColor Aqua
title Links flow diagram between applications

'Objects
[Links]

'Packages
package "Bookmarks Apps" {
  [Links]-[#red]->[Refind Collections] : saved in
  [Refind]-[#green]->[Links] : generate
  [Refind]..>[Refind Collections]
  [Tagpacker] #lightgrey
  [Links]-[#red]->[Tagpacker] : saved in
  note right of [Tagpacker] #lightgreen : removed
  [Links]-[#red]->[Diigo] : saved in
  interface "Add Link" as AL
  AL - [Diigo]
}
package "Social Media Apps" {
  [Twitter]-[#green]->[Links] : generate
  [Reddit]-[#green]->[Links] : generate
  package "Facebook" {
    [Facebook]-[#green]->[Links] : generate
    [Links]-[#red]->[Facebook Saved] : saved in
    
    [Facebook]..>[Facebook Saved]
    [Facebook Saved]-[#green,dotted]->[Diigo]
  }
  package "Pinterest" {
    [Pinterest]-[#green]->[Links] : generate
    [Links]-[#red]->[Pinterest Boards] : saved in
    [Pinterest]..>[Pinterest Boards]
  }
}
package "Chat Apps" {
  [WhatsApp]-[#green]->[Links] : generate
  [Messenger]-[#green]->[Links] : generate
  [Links]-[#red]->[Slack Channels] : saved in
}
package "Media Apps" {
  [YouTube]-[#green]->[Links] : generate
  [Links]-[#red]->[YouTube Playlists] : saved in
  [YouTube]..>[YouTube Playlists]
  [Shazam]-[#green]->[Links] : generate
  [Google Podcasts]-[#green]->[Links] : generate
  package "Sound Cloud" {
    [Sound Cloud]-[#green]->[Links] : generate
    [Links]-[#red]->[Sound Cloud Playlists] : saved in
    [Sound Cloud]..>[Sound Cloud Playlists]
  }
}
package "Note Taking Apps" {
  [Links]-[#red]->[Notion] : saved in
  [Links]-[#red]->[Evernote] : saved in
  [Links]-[#red]->[1 Second Note] : saved in
  [1 Second Note]..>[Evernote] : sync to
}
package "Emails" {
  [Links]-[#red]->[GMail] : saved in
  [Links]-[#red]->[Outlook] : saved in
}
package "Browsers" {
  [Chrome Bookmarks] #lightgrey
  [Session Buddy] #lightgrey
  [Firefox Bookmarks] #lightgrey
  [Links]-[#red]->[Chrome Bookmarks] : saved in
  [Links]-[#red]->[Firefox Bookmarks] : saved in
  [Links]-[#red]->[IE Bookmarks] : saved in
  [Links]-[#red]->[Session Buddy] : saved in
}
package "Stack Exchange" {
  [Stack Exchange]-[#green]->[Links] : generate
  [Links]-[#red]->[Stack Exchange Favorite] : saved in
  [Stack Exchange]..>[Stack Exchange Favorite]
}
package "Google Play" {
  [Google Play]-[#green]->[Links] : generate
  [Links]-[#red]->[Google Play Wishlist] : saved in
  [Links]-[#red]->[Google Play Installed] : saved in
}
package "Github" {
  [Github]-[#green]->[Links] : generate
  [Links]-[#red]->[Github Starred] : saved in
  [Github]..>[Github Starred]
}
package "Other Apps" {
  [Google Discover]-[#green]->[Links] : generate
  [Contacts+]-[#green]->[Links] : generate
  [Links]-[#red]->[Maps] : saved in
  [Links]-[#red]->[Passpack] : saved in
}
@enduml